apiVersion: v1
kind: Secret
metadata:
  name: hcloud-talos-poc-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: hcloud-talos-poc
  server: https://kube.example.com:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<BASE64_CA_CERT>",
        "certData": "<BASE64_CLIENT_CERT>",
        "keyData": "<BASE64_CLIENT_KEY>"
      }
    }
